In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
df = pd.read_csv('../../data/raw/billings.csv')
df.head()

C:\Users\gopik\AppData\Local\Temp\ipykernel_2936\936755889.py:1: DtypeWarning: Columns (0: Proforma_Auto_Renewal, 1: Proforma_World_Pay_Token, 2: Current_Anchor_List, 3: Last_Renewal, 4: Last_Band) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../../data/raw/billings.csv')

,Co_Ref,Renewal_Month,Connection_Net,Connection_Qty,Discount_Amount,Sustainability_Score,Total_Renewal_Score_New,Starting_Connection_Net,Starting_Connection_Qty,Last_Years_Price,...,Connection_Group,Tenure_Group,#_of_Connection,Last_Renewal,Last_Band,Last_Total_Net_Paid,Last_Connections,Anchor_Group,Renewal_Year,DateTime_Out
0,VT6174,01-11-2024,NaN,NaN,NaN,8.0,42.5,NaN,NaN,799.0,...,1,3,1.0,01-11-2023,Band B,664.0,1.0,1,2024,01-11-2024
1,VD3828,01-08-2025,NaN,NaN,NaN,8.0,41.5,NaN,NaN,799.0,...,1,1,1.0,NaN,NaN,NaN,NaN,1,2025,01-08-2025
2,DV8120,01-03-2025,NaN,NaN,NaN,8.0,33.0,NaN,NaN,799.0,...,1,4+,1.0,01-03-2024,Band C1,749.0,1.0,1,2025,01-03-2025
3,EZ9894,01-06-2025,NaN,NaN,NaN,9.5,44.5,NaN,NaN,799.0,...,1,4+,1.0,01-06-2024,Band C1,749.0,1.0,1,2025,01-06-2025
4,FA8957,01-03-2025,NaN,NaN,NaN,9.5,42.5,NaN,NaN,799.0,...,1,3,1.0,01-03-2024,Band C1,749.0,1.0,1,2025,01-03-2025

In [47]:
df.shape

(122082, 59)

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 122082 entries, 0 to 122081
Data columns (total 59 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Co_Ref                      122082 non-null  str
 1   Renewal_Month               122082 non-null  str
 2   Connection_Net              8037 non-null    float64
 3   Connection_Qty              8037 non-null    float64
 4   Discount_Amount             13551 non-null   str
 5   Sustainability_Score        122082 non-null  float64
 6   Total_Renewal_Score_New     122082 non-null  float64
 7   Starting_Connection_Net     8545 non-null    float64
 8   Starting_Connection_Qty     8545 non-null    float64
 9   Last_Years_Price            112992 non-null  float64
 10  Last_Years_Date_Paid        0 non-null       float64
 11  Auto_Renewal_Score          122082 non-null  int64
 12  Status_Scores               122082 non-null  int64
 13  Anchoring_Score             122082 non-null  float64
 14  Tenure_Scores               122082 non-null  float64
 15  Proforma_Auto_Renewal       104030 non-null  object
 16  Proforma_World_Pay_Token    104030 non-null  object
 17  Proforma_Date               121778 non-null  str
 18  Current_Anchorings          122082 non-null  int64
 19  Current_Anchor_List         96125 non-null   str
 20  Payment_Timeframe           101226 non-null  float64
 21  Registration_Date           121064 non-null  str
 22  Proforma_Account_Stage      112853 non-null  str
 23  Proforma_Audit_Status       112853 non-null  str
 24  Current_Auto_Renewal_Flag   122082 non-null  str
 25  Current_World_Pay_Token     122082 non-null  str
 26  Renewal_Score_At_Release    121956 non-null  float64
 27  Proforma_Membership_Status  121956 non-null  str
 28  Proforma_Approved_Lists     121956 non-null  float64
 29  Tenure_Years                121064 non-null  float64
 30  Band                        122058 non-null  str
 31  Prospect_Renewal_Date       122082 non-null  str
 32  Closed_Date                 113894 non-null  str
 33  Prospect_Status             122082 non-null  str
 34  Starting_Net                122082 non-null  int64
 35  Starting_Vat                122082 non-null  float64
 36  Starting_Gross              122082 non-null  float64
 37  Starting_Membership_Net     122082 non-null  int64
 38  Starting_Package_Net        122082 non-null  int64
 39  Starting_PQQ_Net            122082 non-null  int64
 40  Gross                       122082 non-null  float64
 41  Membership_Net              122082 non-null  float64
 42  Package_Net                 122082 non-null  float64
 43  PQQNet                      122082 non-null  int64
 44  Total_Net_Paid              101226 non-null  float64
 45  Prospect_Outcome            122082 non-null  str
 46  Payment_Method              122082 non-null  str
 47  Amount                      122082 non-null  int64
 48  Total_Amount                122082 non-null  float64
 49  Connection_Group            121956 non-null  str
 50  Tenure_Group                121064 non-null  str
 51  #_of_Connection             121956 non-null  float64
 52  Last_Renewal                73791 non-null   str
 53  Last_Band                   73771 non-null   str
 54  Last_Total_Net_Paid         73726 non-null   float64
 55  Last_Connections            73702 non-null   float64
 56  Anchor_Group                121956 non-null  str
 57  Renewal_Year                122082 non-null  int64
 58  DateTime_Out                122082 non-null  str
dtypes: float64(24), int64(10), object(2), str(23)
memory usage: 55.0+ MB

In [49]:
df.describe()

,Connection_Net,Connection_Qty,Sustainability_Score,Total_Renewal_Score_New,Starting_Connection_Net,Starting_Connection_Qty,Last_Years_Price,Last_Years_Date_Paid,Auto_Renewal_Score,Status_Scores,...,Membership_Net,Package_Net,PQQNet,Total_Net_Paid,Amount,Total_Amount,#_of_Connection,Last_Total_Net_Paid,Last_Connections,Renewal_Year
count,8037.000000,8037.000000,122082.000000,122082.000000,8545.000000,8545.000000,112992.000000,0.0,122082.000000,122082.000000,...,122082.000000,122082.000000,122082.000000,101226.000000,122082.000000,122082.000000,121956.000000,73726.000000,73702.000000,122082.000000
mean,418.268259,5.799925,8.619530,41.983319,463.591223,6.419310,1063.854763,NaN,8.479506,7.187685,...,848.107740,60.233556,133.188996,1077.907507,1107.750864,1069.066063,3.198670,993.923497,3.547773,2024.300290
std,623.568386,7.608354,0.692765,4.291603,685.366345,8.401839,694.584676,NaN,0.499582,3.263780,...,533.440504,67.069747,48.608783,651.303068,689.139920,675.506405,6.548384,518.252054,6.951354,1.029394
min,55.000000,1.000000,8.000000,30.500000,55.000000,1.000000,0.000000,NaN,8.000000,0.000000,...,0.000000,0.000000,-529.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2023.000000
25%,99.000000,1.000000,8.000000,41.500000,110.000000,2.000000,664.000000,NaN,8.000000,7.000000,...,500.000000,0.000000,99.000000,684.000000,699.000000,684.000000,1.000000,684.000000,1.000000,2023.000000
50%,220.000000,3.000000,8.000000,43.500000,225.000000,3.000000,919.000000,NaN,8.000000,9.000000,...,674.000000,0.000000,135.000000,924.000000,934.000000,919.000000,1.000000,869.000000,2.000000,2024.000000
75%,474.000000,7.000000,9.500000,45.000000,495.000000,7.000000,1264.000000,NaN,9.000000,9.000000,...,1014.000000,120.000000,135.000000,1269.000000,1274.000000,1239.000000,3.000000,1149.000000,4.000000,2025.000000
max,4752.000000,48.000000,9.500000,46.500000,4752.000000,48.000000,18326.000000,NaN,9.000000,9.000000,...,13245.000000,225.000000,1930.000000,18326.000000,19927.000000,18326.000000,197.000000,12616.000000,197.000000,2050.000000

## Converting column names to snakecase

In [50]:
import sys
import os
sys.path.append(os.path.abspath('../..'))

In [51]:
from src import utils
df = utils.convert_columns_to_snake_case(df)

## Checking duplicate record

In [52]:
df.duplicated(subset=['co_ref', 'renewal_year']).sum()

np.int64(0)

## Checking null values

In [53]:
(df.isnull().mean() * 100).sort_values(ascending=False)

last_years_date_paid          100.000000
connection_qty                 93.416720
connection_net                 93.416720
starting_connection_net        93.000606
starting_connection_qty        93.000606
discount_amount                88.900084
last_connections               39.629102
last_total_net_paid            39.609443
last_band                      39.572582
last_renewal                   39.556200
current_anchor_list            21.261939
payment_timeframe              17.083600
total_net_paid                 17.083600
proforma_auto_renewal          14.786783
proforma_world_pay_token       14.786783
proforma_account_stage          7.559673
proforma_audit_status           7.559673
last_years_price                7.445815
closed_date                     6.706967
tenure_years                    0.833866
tenure_group                    0.833866
registration_date               0.833866
proforma_date                   0.249013
renewal_score_at_release        0.103209
proforma_approved_lists         0.103209
connection_group                0.103209
of_connection                   0.103209
anchor_group                    0.103209
proforma_membership_status      0.103209
band                            0.019659
status_scores                   0.000000
current_world_pay_token         0.000000
current_auto_renewal_flag       0.000000
current_anchorings              0.000000
sustainability_score            0.000000
renewal_month                   0.000000
co_ref                          0.000000
total_renewal_score_new         0.000000
auto_renewal_score              0.000000
tenure_scores                   0.000000
anchoring_score                 0.000000
prospect_status                 0.000000
prospect_renewal_date           0.000000
package_net                     0.000000
membership_net                  0.000000
gross                           0.000000
starting_pqq_net                0.000000
starting_package_net            0.000000
starting_membership_net         0.000000
starting_gross                  0.000000
starting_vat                    0.000000
starting_net                    0.000000
amount                          0.000000
prospect_outcome                0.000000
payment_method                  0.000000
pqqnet                          0.000000
total_amount                    0.000000
renewal_year                    0.000000
datetime_out                    0.000000
dtype: float64

## Dropping fully null column

In [54]:
df.drop(columns=['last_years_date_paid'], inplace=True)

## Dropping >90% Null Columns

In [55]:
df.drop(columns=['connection_net','connection_qty','starting_connection_net','starting_connection_qty'], inplace=True)

## Removal of Leakage Columns

In [56]:
df.drop(columns=[
    'closed_date',
    'prospect_status',
    'total_net_paid',
    'gross'
], inplace=True)

## Detecting duplicate columns

In [57]:
duplicates = []
cols = df.columns.tolist()

for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        c1, c2 = cols[i], cols[j]
        if df[c1].astype(str).equals(df[c2].astype(str)):
            duplicates.append((c1, c2))

for c1, c2 in duplicates:
    print(f"{c1}  ==  {c2}")

renewal_month  ==  datetime_out
proforma_approved_lists  ==  of_connection
starting_net  ==  amount
connection_group  ==  anchor_group

## Fixing of duplicate columns

In [58]:
df.drop(columns=[
    'datetime_out',     # duplicate of Renewal_Month
    'of_connection',     # duplicate of Proforma_Approved_Lists
    'amount',           # duplicate of Starting_Net
    'connection_group',    # duplicate of Anchor_Group
], inplace=True)

## Handling missing values

In [59]:
# Create a flag to identify first year customers
# If last_renewal is null then first year(1), else returning (0)
df['is_first_year'] = df['last_renewal'].isnull().astype(int)

# Fill missing previous payment with current price
# Assumes first year customers paid similar to current starting_net
df['last_total_net_paid'] =df['last_total_net_paid'].fillna(df['starting_net'], inplace=True)

# Fill missing previous connections with 0
# First year customers had no prior connections
df['last_connections'] = df['last_connections'].fillna(0, inplace=True)

# Fill missing previous band with current band
# Assumes no change in band for first year customers
df['last_band']=df['last_band'].fillna(df['band'], inplace=True)

# Fill missing previous renewal date with current renewal date
# Avoids issues in time based calculations for first year customers
df['last_renewal'] = df['last_renewal'].fillna(df['prospect_renewal_date'], inplace=True)

C:\Users\gopik\AppData\Local\Temp\ipykernel_2936\443916521.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['last_total_net_paid'] =df['last_total_net_paid'].fillna(df['starting_net'], inplace=True)
C:\Users\gopik\AppData\Local\Temp\ipykernel_2936\443916521.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['last_connections'] = df['last_connections'].fillna(0, inplace=True)
C:\Users\gopik\AppData\Local\Temp\ipykernel_2936\443916521.py:15: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['last_band']=df['last_band'].fillna(df['band'], inplace=True)
C:\Users\gopik\AppData\Local\Temp\ipykernel_2936\443916521.py:19: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['last_renewal'] = df['last_renewal'].fillna(df['prospect_renewal_date'], inplace=True)

In [60]:
# Null means no discount was given
df['has_discount'] = df['discount_amount'].notna().astype(int)

# Parse the % string to float for the rows that have it
df['discount_pct'] = (
    df['discount_amount']
    .str.replace('%', '', regex=False)
    .astype(float) / 100
)
df['discount_pct'] = df['discount_pct'].fillna(0, inplace=True)

df.drop(columns=['discount_amount'], inplace=True)

C:\Users\gopik\AppData\Local\Temp\ipykernel_2936\418585642.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['discount_pct'] = df['discount_pct'].fillna(0, inplace=True)

In [61]:
df['payment_timeframe']= df['payment_timeframe'].fillna(0, inplace=True) # 0 = not yet paid

C:\Users\gopik\AppData\Local\Temp\ipykernel_2936\1931014501.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['payment_timeframe']= df['payment_timeframe'].fillna(0, inplace=True) # 0 = not yet paid