In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys, os

In [76]:
# sys.path.append(os.path.abspath("../.."))
sys.path

['/opt/homebrew/Caskroom/miniconda/base/envs/spark/lib/python311.zip',
 '/opt/homebrew/Caskroom/miniconda/base/envs/spark/lib/python3.11',
 '/opt/homebrew/Caskroom/miniconda/base/envs/spark/lib/python3.11/lib-dynload',
 '',
 '/opt/homebrew/Caskroom/miniconda/base/envs/spark/lib/python3.11/site-packages',
 '/Users/gauravrathore/Desktop/churn-prediction-project/notebooks',
 '/Users/gauravrathore/Desktop/churn-prediction-project']

In [64]:
from src import utils

In [83]:
pd.set_option('display.max_columns', None)

In [84]:
df = pd.read_csv('../../data/raw/emails.csv')

/var/folders/47/spc9kf0x5xngx2jj19_8vgj00000gn/T/ipykernel_34267/496971227.py:1: DtypeWarning: Columns (16,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../../data/raw/emails.csv')

In [85]:
df.head()

,Co_Ref,Time_to_Renewal,crm_accreditation_completed,crm_timely_completion,crm_progress_towards_accreditation,crm_delays_in_accreditation,crm_contractor_suggested_leave,crm_contractor_engagement,crm_contractor_sentiment,crm_contractor_sentiment_score,crm_dts_or_ssip_mentioned,crm_customer_payment_intention,crm_competitors_mentioned,crm_membership_level,crm_platform_issues_raised,crm_agent_chased_contractor,crm_agent_chase_count,crm_accreditation_issues,crm_membership_overdue,crm_auto_renewal_status,crm_dissatisified_with_renewal_price,crm_customer_complained,crm_refund_mentioned,crm_negative_customer_experience,crm_dissatisfaction_with_support,crm_financial_hardship_mentioned,year
0,KG5766,pre_renewal,Not Discussed,Not Discussed,Not Discussed,Yes,No,Yes,Neutral,50,No,No,No,Not Discussed,No,Yes,1,Not Discussed,Yes,0,No,No,Yes,Yes,No,Yes,2025
1,EJ1532,14_out,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,No,Not Discussed,No,Accredited,No,Yes,1,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
2,AA4063,prior_year,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Neutral,50,No,Yes,No,Accredited,No,No,0,Not Discussed,No,0,No,No,Yes,Yes,Yes,Not Discussed,2025
3,JY9888,prior_year,No,No,Not Discussed,Yes,No,Yes,Satisfied,80,Yes,Yes,No,Accredited,Yes,Yes,3,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
4,WO6689,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Satisfied,80,No,Yes,No,Accredited,No,No,0,No,No,0,No,No,Yes,Yes,No,Not Discussed,2026

In [86]:
df.shape

(123389, 27)

## convert column names to snakecase

In [87]:
df = utils.convert_columns_to_snake_case(df)

## Identifying numerical and categorical data

In [88]:
df.dtypes

co_ref                                  object
time_to_renewal                         object
crm_accreditation_completed             object
crm_timely_completion                   object
crm_progress_towards_accreditation      object
crm_delays_in_accreditation             object
crm_contractor_suggested_leave          object
crm_contractor_engagement               object
crm_contractor_sentiment                object
crm_contractor_sentiment_score          object
crm_dts_or_ssip_mentioned               object
crm_customer_payment_intention          object
crm_competitors_mentioned               object
crm_membership_level                    object
crm_platform_issues_raised              object
crm_agent_chased_contractor             object
crm_agent_chase_count                   object
crm_accreditation_issues                object
crm_membership_overdue                  object
crm_auto_renewal_status                 object
crm_dissatisified_with_renewal_price    object
crm_customer_complained                 object
crm_refund_mentioned                    object
crm_negative_customer_experience        object
crm_dissatisfaction_with_support        object
crm_financial_hardship_mentioned        object
year                                     int64
dtype: object

In [89]:
df.nunique()

co_ref                                  37964
time_to_renewal                             4
crm_accreditation_completed                 3
crm_timely_completion                       3
crm_progress_towards_accreditation          3
crm_delays_in_accreditation                18
crm_contractor_suggested_leave              3
crm_contractor_engagement                  28
crm_contractor_sentiment                   12
crm_contractor_sentiment_score             52
crm_dts_or_ssip_mentioned                   9
crm_customer_payment_intention              6
crm_competitors_mentioned                   5
crm_membership_level                       57
crm_platform_issues_raised                  3
crm_agent_chased_contractor                 3
crm_agent_chase_count                     114
crm_accreditation_issues                    3
crm_membership_overdue                     53
crm_auto_renewal_status                    15
crm_dissatisified_with_renewal_price        6
crm_customer_complained                    14
crm_refund_mentioned                       27
crm_negative_customer_experience            8
crm_dissatisfaction_with_support           57
crm_financial_hardship_mentioned           11
year                                        3
dtype: int64

In [91]:
df['time_to_renewal'].value_counts()

time_to_renewal
prior_year     40022
14_out         32493
45_out         28008
pre_renewal    22866
Name: count, dtype: int64

In [92]:
df['time_to_renewal'].isnull().sum()

np.int64(0)

## in column 'time_to_renewal' we can find pre_renewal category and filter out data which is relevant to our use case

In [93]:
df = df[df['time_to_renewal'] == 'pre_renewal']

In [94]:
df

,co_ref,time_to_renewal,crm_accreditation_completed,crm_timely_completion,crm_progress_towards_accreditation,crm_delays_in_accreditation,crm_contractor_suggested_leave,crm_contractor_engagement,crm_contractor_sentiment,crm_contractor_sentiment_score,crm_dts_or_ssip_mentioned,crm_customer_payment_intention,crm_competitors_mentioned,crm_membership_level,crm_platform_issues_raised,crm_agent_chased_contractor,crm_agent_chase_count,crm_accreditation_issues,crm_membership_overdue,crm_auto_renewal_status,crm_dissatisified_with_renewal_price,crm_customer_complained,crm_refund_mentioned,crm_negative_customer_experience,crm_dissatisfaction_with_support,crm_financial_hardship_mentioned,year
0,KG5766,pre_renewal,Not Discussed,Not Discussed,Not Discussed,Yes,No,Yes,Neutral,50,No,No,No,Not Discussed,No,Yes,1,Not Discussed,Yes,0,No,No,Yes,Yes,No,Yes,2025
4,WO6689,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Satisfied,80,No,Yes,No,Accredited,No,No,0,No,No,0,No,No,Yes,Yes,No,Not Discussed,2026
6,SB4066,pre_renewal,Not Discussed,Not Discussed,Not Discussed,Yes,No,Yes,Neutral,50,No,Yes,Not Discussed,Not Discussed,Not Discussed,Yes,3,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2026
7,YK0304,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Yes,No,0,Not Discussed,Not Discussed,0,Not Discussed,No,Yes,Yes,Yes,Not Discussed,2025
8,HH3570,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,No,Yes,Satisfied,80,Yes,Yes,No,Accredited,No,Yes,1,Not Discussed,Yes,0,Not Discussed,No,Yes,Yes,No,Not Discussed,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123338,ZZ9369,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,No,Not Discussed,Not Discussed,Not Discussed,Not Discussed,No,0,Not Discussed,Not Discussed,0,Not Discussed,No,No,Not Discussed,Not Discussed,Not Discussed,2025
123342,WO3900,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,No,Not Discussed,Not Discussed,Not Discussed,Not Discussed,No,0,Not Discussed,Not Discussed,0,Not Discussed,No,No,Not Discussed,Not Discussed,Not Discussed,2025
123345,JQ2250,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,No,Not Discussed,Not Discussed,Not Discussed,Not Discussed,No,0,Not Discussed,Not Discussed,0,Not Discussed,No,No,Not Discussed,Not Discussed,Not Discussed,2025
123348,RQ3555,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,No,Not Discussed,Not Discussed,Not Discussed,Not Discussed,No,0,Not Discussed,Not Discussed,0,Not Discussed,No,No,Not Discussed,Not Discussed,Not Discussed,2025
123351,TD7281,pre_renewal,Not Discussed,Not Discussed,Not Discussed,No,Not Discussed,No,Not Discussed,Not Discussed,No,Not Discussed,Not Discussed,Not Discussed,Not Discussed,No,0,Not Discussed,Not Discussed,0,Not Discussed,No,No,Not Discussed,Not Discussed,Not Discussed,2025

### Most of the columns contain categorical data and mixed data such as numerical and string. 'Not Discussed' is used in place of nulls

In [107]:
for col in df.columns:
    print(df[col].value_counts())
    print('nulls: ', df[col].isnull().sum())
    print('-' * 100)

co_ref
JM8979    3
QE7976    3
NU6835    2
KI4313    2
XT9837    2
         ..
GM7451    1
RW8178    1
IX3469    1
QW9278    1
TD7281    1
Name: count, Length: 21362, dtype: int64
nulls:  0
----------------------------------------------------------------------------------------------------
time_to_renewal
pre_renewal    22866
Name: count, dtype: int64
nulls:  0
----------------------------------------------------------------------------------------------------
crm_accreditation_completed
Not Discussed    10722
No                6742
Yes               2247
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_timely_completion
Not Discussed    17824
No                1474
Yes                413
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_progress_towards_accreditation
Not Discussed    13790
Yes               5343
No                 578
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_delays_in_accreditation
No                                                                                                                            14986
Yes                                                                                                                            4464
Not Discussed                                                                                                                   259
Not Discussed but potentially yes as the customer is trying to contact Ian and was told he may be in later or the next day        1
Not Discussed but potentially yes due to lack of progress                                                                         1
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_contractor_suggested_leave
No               14480
Not Discussed     2649
Yes               2582
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_contractor_engagement
Yes                                                                                                12361
No                                                                                                  7342
Not Discussed                                                                                          4
 indicating dissatisfaction with the cost."                                                            1
 and they have chosen to drop clients that require the certification."                                 1
"" indicating dissatisfaction with their previous experience."                                         1
 indicating a loss of interest in pursuing the accreditation process with the current company."        1
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_contractor_sentiment
Neutral                                  8612
Not Discussed                            7337
Satisfied                                2254
Dissatisfied                             1503
Yes                                         3
Initially Dissatisfied, later Neutral       1
No                                          1
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_contractor_sentiment_score
50               8609
Not Discussed    7338
80               1449
20                811
90                577
0                 282
30                238
100               225
40                168
Dissatisfied        2
70                  1
25.5                1
Neutral             1
98                  1
31                  1
16                  1
55                  1
48                  1
91                  1
84                  1
60                  1
96                  1
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_dts_or_ssip_mentioned
No               15478
Yes               4229
30                   1
0                    1
50                   1
Not Discussed        1
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_customer_payment_intention
Not Discussed    11323
Yes               6325
No                2063
Name: count, dtype: int64
nulls:  3155
----------------------------------------------------------------------------------------------------
crm_competitors_mentioned
No               15849
Not Discussed     5031
Yes                468
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_membership_level
Not Discussed                8374
Accredited                   7153
In progress                  5621
Members only                  101
Not Accredited                 70
Standard                        9
Membership (Standard)           5
Standard membership             3
Gold                            2
Standard membership level       2
Prem                            1
Accredited (Gold level)         1
Premier Band B                  1
Premier package                 1
Silver                          1
Premier Band C2                 1
Premier services                1
Express membership level        1
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_platform_issues_raised
No               15751
Not Discussed     4561
Yes               1036
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_agent_chased_contractor
Yes              12987
No                8258
Not Discussed      103
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_agent_chase_count
1                                                                         5986
0                                                                         4290
0                                                                         4069
2                                                                         3818
1                                                                         2139
3                                                                          824
4                                                                          106
5                                                                           31
Not Discussed                                                               14
Multiple                                                                    10
6                                                                            9
Not specified                                                                7
A few                                                                        7
7                                                                            5
Several                                                                      3
More than 7                                                                  2
10                                                                           2
A number of times (no specific number mentioned)                             2
Multiple (exact number not specified)                                        1
Multiple times (via phone and email)                                         1
Many                                                                         1
A few times (no exact number specified)                                      1
Multiple ( exact number not specified)                                       1
Not specified, but multiple attempts were made by the audit team             1
8                                                                            1
Multiple times throughout June                                               1
A few times                                                                  1
A number of months                                                           1
Multiple times ( exact number not specified)                                 1
Not explicitly stated, but implied to be multiple times                      1
Multiple times from March until May-June                                     1
2 (at least, as the agent mentioned sending emails and making a call)        1
Numerous occasions (no specific number mentioned)                            1
Multiple times, exact number not specified                                   1
Multiple times (since December)                                              1
Not applicable (only chased a few times, no specific number mentioned)       1
Not applicable (multiple times)                                              1
13                                                                           1
11                                                                           1
Multiple times (exact number not specified)                                  1
Multiple times weekly                                                        1
Multiple (weekly reminders from 30 days before the due date)                 1
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_accreditation_issues
Not Discussed    15251
Yes               3219
No                2878
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_membership_overdue
Yes                                                               9460
Not Discussed                                                     7875
No                                                                4008
 which they requested to be removed and the invoice reissued."       1
 your call cannot me connected at present""."                        1
Almost expired                                                       1
 which was required for the audit to proceed."                       1
 professional indemnity                                              1
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_auto_renewal_status
0                              13549
0                               6429
2                               1226
1                                140
Not Discussed                      3
 and employer's liability."        1
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_dissatisified_with_renewal_price
Not Discussed    14649
No                5374
Yes               1322
0                    3
Name: count, dtype: int64
nulls:  1518
----------------------------------------------------------------------------------------------------
crm_customer_complained
No                                                          19721
Yes                                                          1512
[Yes/No]                                                        1
Not applicable (there is no email content to analyze)           1
Not Applicable (since there is no call content provided)        1
Name: count, dtype: int64
nulls:  1630
----------------------------------------------------------------------------------------------------
crm_refund_mentioned
No                                                              20928
Yes                                                               301
 which the agent was not aware of."                                 1
 and then hung up."                                                 1
 indicating dissatisfaction."                                       1
[Yes/No]                                                            1
 completing window work without SafeContractor accreditation        1
Not applicable (there is no email content to analyze)               1
Not Discussed                                                       1
Name: count, dtype: int64
nulls:  1630
----------------------------------------------------------------------------------------------------
crm_negative_customer_experience
No                                                       11959
Not Discussed                                             5560
Yes                                                       3714
[Yes/No/Not Discussed]                                       1
 causing them to lose work."                                 1
Not applicable (there is no email content to analyze)        1
Name: count, dtype: int64
nulls:  1630
----------------------------------------------------------------------------------------------------
crm_dissatisfaction_with_support
No                                                                                                                                                      11628
Not Discussed                                                                                                                                            8083
Yes                                                                                                                                                      1510
 indicating a negative experience."                                                                                                                         1
"" and being busy with ISO work."                                                                                                                           1
[Yes/No/Not Discussed]                                                                                                                                      1
 indicating a sense of urgency and annoyance."                                                                                                              1
"" indicating a negative experience."                                                                                                                       1
 indicating a lack of value in the SafeContractor membership."                                                                                              1
 indicating dissatisfaction with the accreditation/audit process."                                                                                          1
 indicating a negative experience with a client."                                                                                                           1
 indicating a potential financial issue."                                                                                                                   1
"The Contractor appeared to be dissatisfied, as evidenced by their request to ""shut it down"" during the call."                                            1
The Contractor had a negative experience when they received an unexpected or unwanted call, leading to an explicit outburst and abrupt hang-up.             1
The Contractor had a negative experience because their expectations for the call were not met, leading to frustration and the call being terminated.        1
 which led to a last-minute and urgent request to resolve the payment."                                                                                     1
 invalid address                                                                                                                                            1
Not applicable (there is no email content to analyze)                                                                                                       1
Name: count, dtype: int64
nulls:  1630
----------------------------------------------------------------------------------------------------
crm_financial_hardship_mentioned
Not Discussed                                                                                                                                   15608
No                                                                                                                                               4305
Yes                                                                                                                                              1309
Yes                                                                                                                                                10
 city is required"" message."                                                                                                                       1
[Yes/No/Not Discussed]                                                                                                                              1
"The Contractor expressed frustration due to the issue with ""24 hour locksmiths"" and the inconvenience with the payment link not working."        1
Not applicable (there is no email content to analyze)                                                                                               1
Name: count, dtype: int64
nulls:  1630
----------------------------------------------------------------------------------------------------
year
2025    15065
2026     7801
Name: count, dtype: int64
nulls:  0
----------------------------------------------------------------------------------------------------

In [108]:
df.dtypes

co_ref                                  object
time_to_renewal                         object
crm_accreditation_completed             object
crm_timely_completion                   object
crm_progress_towards_accreditation      object
crm_delays_in_accreditation             object
crm_contractor_suggested_leave          object
crm_contractor_engagement               object
crm_contractor_sentiment                object
crm_contractor_sentiment_score          object
crm_dts_or_ssip_mentioned               object
crm_customer_payment_intention          object
crm_competitors_mentioned               object
crm_membership_level                    object
crm_platform_issues_raised              object
crm_agent_chased_contractor             object
crm_agent_chase_count                   object
crm_accreditation_issues                object
crm_membership_overdue                  object
crm_auto_renewal_status                 object
crm_dissatisified_with_renewal_price    object
crm_customer_complained                 object
crm_refund_mentioned                    object
crm_negative_customer_experience        object
crm_dissatisfaction_with_support        object
crm_financial_hardship_mentioned        object
year                                     int64
dtype: object